SPAM=[
    "jobs matching your saved search",
    "job recommendations",
    "new jobs for",
    "hackathon",
    "your profile is a match",
    "apply to jobs at",
    "hiring now",
    "explore new jobs",
    "opportunities at",
    "naukri",
    "foundit",
    "matching jobs",
    "hot jobs",
    "job alert",
    "recommended jobs",
    "top jobs",
    "based on your preferences",
    "opportunities waiting",
    "10+",
    "top jobs",
    "matching jobs",
    "hot job",
    "daily jobs",
    "based on your profile",
    "saved search",
    "you haven't applied",
    "roles are closing",
    "back your decisions",
    "last chance",
    "save 20%",
    "coding contest",
]
def is_spam(subject: str) -> bool:
    subject=subject.lower()
    return any(phrase in subject for phrase in SPAM)        